Feature/pvt events v.0.1.0
simandebvu/private-events pull request #1
Opened 2020-07-24 16:41 UTC by ricardo123321

We created a private events page that allows us to make and attend events that belong to different users and we establish numerous methods of validations so the information provided will be one acceptable, and those who are not signed can see the events, but those who sign can attend and leave the events and see who made them and the upcoming or past events

2020-07-24 21:15 UTC, kobiyoyo requested changes
## Hi Team    ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, but there are a few more things required. 
### General
- [x] Let's fix the broken image in the readme.MD file
- [x] SInce we are not building API's lets remove all the `format.json`
- [x] There should be NO application logic in the views nor helpers (no `Post.new`, `Comment.create`, `current_user.friends.find_by(...)`...). Everything connected with data processing should be encapsulated in models and used in controllers.
- [x] In the user's show page, events need to be separated( past and upcoming events)
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-07-24 21:15 UTC, kobiyoyo commented on app/controllers/events_controller.rb
> +    # @event = @current_user1.events.build(event_params)
Comments: It’s better to delete commented piece of codes. If you need to review a previous version of your code, use git history.

2020-07-24 21:15 UTC, kobiyoyo commented on app/controllers/events_controller.rb
> +        format.json { render :show, status: :created, location: @event }
- [x] You don't need this rendered in JSON ,let remove this.

2020-07-24 21:15 UTC, kobiyoyo commented on app/controllers/events_controller.rb
> +        format.json { render json: @event.errors, status: :unprocessable_entity }
- [x] You don't need this rendered in JSON ,let remove this.

2020-07-24 21:15 UTC, kobiyoyo commented on app/controllers/events_controller.rb
> +        format.json { render json: @event.errors, status: :unprocessable_entity }
- [x] You don't need this rendered in JSON ,let remove this.

2020-07-24 21:15 UTC, kobiyoyo commented on app/controllers/users_controller.rb
> +  end
###### `show` action

* [x] lists events created by user, i.e. `@created_events = current_user.events` 
* [x] lists events previoulsy attendented by user **using event model scope**, i.e. `@past_events = current_user.attended_events.previous` 
* [x] lists upcoming events previously attended by user **using event model scope**, i.e. `@upcoming_events = current_user.attended_events.upcoming`

2020-07-24 21:15 UTC, kobiyoyo commented on db/schema.rb
> +    t.integer "attended_event_id"
- [ ] Lets index this columns

2020-07-27 15:02 UTC, simandebvu commented on app/controllers/events_controller.rb
> +        format.json { render :show, status: :created, location: @event }
Removed 😄

2020-07-27 15:02 UTC, simandebvu commented on app/controllers/events_controller.rb
> +        format.json { render json: @event.errors, status: :unprocessable_entity }
Removed 😄

2020-07-27 15:02 UTC, simandebvu commented on app/controllers/events_controller.rb
> +        format.json { render json: @event.errors, status: :unprocessable_entity }
Removed 😄

2020-07-27 15:02 UTC, simandebvu commented on app/controllers/events_controller.rb
> +    # @event = @current_user1.events.build(event_params)
Removed 😄

2020-07-27 15:36 UTC, simandebvu commented on db/schema.rb
> +    t.integer "attended_event_id"
Resolved

2020-07-27 15:40 UTC, simandebvu commented on app/controllers/users_controller.rb
> +  end
```
    @events_made_by_current_user = @user.events
    @upcoming_events = @user.attended_events.upcoming_events
    @prev_events = @user.attended_events.previous_events
```

These methods are already in the users controller and then referenced in the show method.

2020-07-27 19:13 UTC, Anna-Myzukina commented
## Hi team :clap: 
### You did a great job so far, but there are a few more things required.


## [REQUIRED]
#### Tests

* [ ] models have unit tests for validations and associations (Rspec) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/unit_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))
* [ ] authentication have has integration tests (Rspec + Capybara) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))
* [ ] event managment features have integration tests (Rspec + Capybara) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))

### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*
*Happy coding * <g-emoji class="g-emoji" alias="computer" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f4bb.png"><img class="emoji" alt="computer" height="25" width="25" src="https://github.githubassets.com/images/icons/emoji/unicode/1f4bb.png"></g-emoji>

2020-07-28 19:31 UTC, stratospherique approved these changes
### Great work implementing the suggested changes :clap: :clap: Congrats, the project is approved :heavy_check_mark: You may merge :+1: :+1: 

Happy coding :v: 
**_Ahmed Mahfoudh_**

2020-07-28 19:32 UTC, simandebvu commented
Thank you for the review and helpful feedback 😄

2020-07-28 19:32 UTC, merged